# ~/.tmuxinator/services.yml
# you can make as many tabs as you wish...

project_name: Services
project_root: ~/src
tabs:
  - sr: cd ~/src/service_registry
  - user: cd ~/src/user_service
  - mds: cd ~/src/metadata_service
  - media: cd ~/src/media_service
  - market: cd ~/src/market_service
  - web_app: cd ~/src/web_app
  - admin_app: cd ~/src/admin_app
  - security: cd ~/src/security_service
  - memcached: memcached
