# ~/.tmuxinator/services.yml
# you can make as many tabs as you wish...

project_name: Services
project_root: ~/src
tabs:
  - sr: cd ~/src/service_registry && script/run_local
  - user: cd ~/src/user_service && script/run_local
  - mds: cd ~/src/metadata_service && script/run_local
  - media: cd ~/src/media_service && script/run_local
  - market: cd ~/src/market_service && script/run_local
  - web_app: cd ~/src/web_app && script/run_local
  - admin_app: cd ~/src/admin_app && script/run_local
  - security: cd ~/src/security_service && script/run_local
  - memcached: memcached
