#!/usr/bin/env rake

$root = Dir.home << '/src'

def each_dir(&block)
  Dir.foreach($root) { |x|
    if File.directory? x
      unless x.eql? '.' or x.eql? '..'
        Dir.chdir "#{$root}/#{x}" do
          block.call("#{$root}/#{x}")
        end
      end
    end
  }
end

task :tags do
  each_dir do |dir|
    puts dir
    `ctags --file-scope=no -R`
  end
end

task :bundle_install do
  each_dir do |dir|
    puts dir
    `bundle install`
  end
end

task :pull_origin do
  each_dir do |dir|
    `git pull origin master`
  end
end

task :pull_huunu do
  each_dir do |dir|
    `git pull huunu master`
  end
end

task :update_gemfile do
  each_dir do |dir|
    `ndk_gemfile`
  end
end
